### ISSUE TITLE
Dark Horse and Dark Raven Unable to save Level

### ISSUE THREAD

**Issue by tangyi90** [kessiler/muOnline-season6#21] opened 2015-09-07 04:39 UTC

**Comment by kessiler** [comment] 2015-10-01 21:33
Duplicate of #20

**Closed** 2015-10-01 21:33 UTC

**Comment by tangyi90** [comment] 2015-10-04 14:27
You can fix this problem as soon as possible under it？

**Comment by kessiler** [comment] 2015-10-07 18:13
Coming soon, i'll fix that.
You can to track in issue #20
